---
title: ICP-MS Data - IBM
output: 
  html_document:
    theme: simplex
    toc: yes
    toc_float:
      collapsed: true
---
# Load packages
```{r}
# Install packages not yet installed
packages <- c("hablar", "readxl", "tidyverse")
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  utils::install.packages(pkgs = packages[!installed_packages])
}
invisible(lapply(packages, library, character.only = TRUE)) # load all packages in list
# install packages not on CRAN
if (!require("remotes")) install.packages("remotes")
rm(installed_packages, packages) # remove objects from environment
```
# Fixing spreadsheet

### Import
```{r}
library(readxl)
library(tidyverse)
path <- "ICP-MS/ICP-MS_rawdata.xlsx"
testing1 <- path %>% 
  excel_sheets() %>% 
  set_names() %>% 
  map(read_xlsx, path = path)
rm(path)
saveRDS(testing1, "RDS_dataframes/ICP-MS_raw.RDS")
```
### Fix specimen/variable names
```{r}
testing <- readRDS("RDS_dataframes/ICP-MS_raw.RDS")
specimen.vars <- c(
  "oto01-0", "oto01-1", "oto01-2", "oto01-3", 
  "oto10-0", "oto10-1", "oto10-2", "oto10-3",
  "oto11-0", "oto11-1", "oto11-2", "oto11-3",
  "oto12-0", "oto12-1", "oto12-2", "oto12-3",
  "oto13-0", "oto13-1", "oto13-2", "oto13-3",
  "oto15-0", "oto15-1", "oto15-2", "oto15-3",
  "oto16-0", "oto16-1", "oto16-2", "oto16-3",
  "oto17-0", "oto17-1", "oto17-2", "oto17-3",
  "oto18-0", "oto18-1", "oto18-2", "oto18-3",
  "oto19-0", "oto19-1", "oto19-2", "oto19-3",
  "oto02-0", "oto02-1", "oto02-2", "oto02-3",
  "oto20-0", "oto20-1", "oto20-2", "oto20-3",
  "oto21-0", "oto21-1", "oto21-2", "oto21-3",
  "oto22-0", "oto22-1", "oto22-2", "oto22-3",
  "oto23-0", "oto23-1", "oto23-2", "oto23-3",
  "oto24-0", "oto24-1", "oto24-2",
  "oto25-0", "oto25-1", "oto25-2", "oto25-3",
  "oto26-0", "oto26-1", "oto26-2", "oto26-3",
  "oto27-0", "oto27-1", "oto27-2", "oto27-3",
  "oto28-0", "oto28-1", "oto28-2", "oto28-3",
  "oto29-0", "oto29-1", "oto29-2", "oto29-3",
  "oto03-0", "oto03-1", "oto03-2", "oto03-3",
  "oto30-0", "oto30-1", "oto30-2", "oto30-3",
  "oto31-0", "oto31-1", "oto31-2", "oto31-3",
  "oto32-0", "oto32-1", "oto32-2", "oto32-3",
  "oto33-0", "oto33-1", "oto33-2", "oto33-3",
  "oto34-0", "oto34-1", "oto34-2", "oto34-3",
  "oto35-0", "oto35-1", "oto35-2", "oto35-3",
  "oto36-0", "oto36-1", "oto36-2", "oto36-3",
  "oto37-0", "oto37-1", "oto37-2", "oto37-3",
  "oto38-0", "oto38-1", "oto38-2", "oto38-3",
  "oto39-0", "oto39-1", "oto39-2", "oto39-3",
  "oto40-0", "oto40-1", "oto40-2", "oto40-3",
  "oto04-0", "oto04-1", "oto04-2", "oto04-3",
  "oto05-0", "oto05-1", "oto05-2", "oto05-3",
  "oto06-0", "oto06-1", "oto06-2", "oto06-3",
  "oto07-0", "oto07-1", "oto07-2", "oto07-3",
  "oto08-0", "oto08-1", "oto08-2", "oto08-3",
  "oto09-0", "oto09-1", "oto09-2", "oto09-3"
)
# fix variable names, order list
specimens <- setNames(testing[30:184], specimen.vars)
specimens = specimens[order(names(specimens))]
rm(specimen.vars)
reference.vars <- c(
"ATHO-1", "ATHO-2", "ATHO-3", "ATHO-4", "ATHO-5",
"BM90-21-1", "BM90-21-2", "BM90-21-3", "BM90-21-4", "BM90-21-5",
"NIST612-1", "NIST612-2", "NIST612-3", "NIST612-4",
"G_NIST612-1", "G_NIST612-2", "G_NIST612-3", "G_NIST612-4", "G_NIST612-5",
"NIST612-5","NIST612-6",
"KL2-1", "KL2-2",
"T1-1", "T1-2", "T1-3"
)
references <- setNames(testing[4:29], reference.vars)
references = references[order(names(references))]
ICP_MS <- c(testing[1:3],references,specimens)
rm(reference.vars,references,specimens,testing)
```
### remove blank rows, weird formatting in sheets
```{r}
testing1 <- ICP_MS
for (i in 4:length(ICP_MS)){
testing2 <- testing1[[i]]
testing2 <- testing2[,-1]
names <- as.vector(unlist(testing2[1,]))
colnames(testing2) <- names
testing2 <- testing2[-1,]
testing1[[i]] <- retype(testing2,)
}
ICP_MS <- testing1
rm(testing1,testing2,i,names)
# saveRDS(ICP_MS, "RDS_dataframes/ICP-MS_clean.RDS")
```
### Make single DF (unlist)
```{r}
ICP_MS <- readRDS("RDS_dataframes/ICP-MS_clean.RDS")
# 30 - 184 are otoliths
df <- ICP_MS[c(30:184)]
names(df)
# no specimen 14
# specimen 24 missing a third scan
for(i in 1:155){
  spec <- names(df[i])
  df[[i]]$specimen <- as.factor(str_sub(spec, start= 0,end = 5))
  df[[i]]$transect <- as.factor(as.numeric(str_sub(spec, start= -1)) + 1)
  rm(spec,i)
}
df <- do.call("rbind", df)
df <- rename(df, "time" = `Elapsed Time`)
saveRDS(df, "RDS_dataframes/ICP-MS_df.RDS")
rm(ICP_MS, df)
```

# Data filtering/cutoffs

### Function to detect otolith boundaries using Cu65
```{r}
detect_otolith_boundaries <- function(data, 
                                    high_threshold = 1000,
                                    min_length = 100,
                                    smooth_window = 3) {
  
  # Apply rolling mean to smooth noise
  smooth_data <- stats::filter(data, 
                             rep(1/smooth_window, smooth_window), 
                             sides = 2)
  
  # Find start boundary
  start_candidates <- which(data[1:(length(data)-1)] > high_threshold & 
                          data[2:length(data)] < high_threshold)
  start_idx <- start_candidates[1]
  
  # Find end boundary
  end_candidates <- which(data[start_idx:length(data)] > high_threshold)[1]
  end_idx <- start_idx + end_candidates - 2
  
  # Validation checks
  if(end_idx - start_idx < min_length) {
    warning("Detected segment shorter than minimum length")
  }
  
  # Return cleaned data segment
  return(list(
    start = start_idx,
    end = end_idx,
    clean_data = data[start_idx:end_idx]
  ))
}

# Function to apply to multiple transects
process_all_transects <- function(transect_list, ...) {
  results <- lapply(transect_list, function(x) {
    detect_otolith_boundaries(x, ...)
  })
  return(results)
}

# Quality control function
check_boundaries <- function(results) {
  lapply(results, function(x) {
    segment_length <- x$end - x$start
    mean_value <- mean(x$clean_data)
    list(
      length = segment_length,
      mean = mean_value,
      valid = segment_length >= 100
    )
  })
}


# For a single transect
result <- detect_otolith_boundaries(df$`oto01-0`$Ca43)

# For multiple transects
all_results <- process_all_transects(transect_list)

# Check quality
quality_metrics <- check_boundaries(all_results)

```



